version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: "nodejs-nextjs"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/nextjs